name: Terraform Plan
description: Run Terraform Plan

inputs:
  working_directory:
    description: "Terraform working directory"
    required: true

  role_to_assume:
    description: "AWS Role to assume"
    required: true

  region:
    description: "AWS Region"
    required: true

  tf_version:
    description: "Terraform version to install"
    required: false
    default: "1.16.1"

runs:
  using: composite

  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: $${{ inputs.region }}

    - name: Bootstrap Terraform
      uses: ./.github/actions/tf-bootstrap
      with:
        terraform_version: ${{ inputs.tf_version }}
        working_directory: ${{ inputs.working_directory }}

    - name: Run TF Plan
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: terraform plan -out=tfplan -input=false

    - name: Upload TF Plan
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: ${{ inputs.working_directory }}/tfplan
