name: TF IAM Destroy
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destory:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Run Destroy
        uses: ./.github/actions/tf-destroy
        with:
          working_directory: ./terraform/iam
          role_to_assume: ${{ secrets.AWS_ROLE }}
          region: ${{ vars.REGION }}
