name: Terraform PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflow/pr.yml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-pr
  cancel-in-progress: true

jobs:
  validate:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inspect OIDC claims
        shell: bash
        run: |
          TOKEN=$(curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
            | jq -r '.value')

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)

          # Decode JWT payload and print only useful claims
          echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{
            iss,
            aud,
            sub,
            repository,
            ref,
            job_workflow_ref
          }'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::118035478456:role/GitHubTFRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -no-color
